-- Inserción de datos en la tabla ESTADOS
INSERT INTO estados ( NOMBRE) VALUES ('Aguascalientes');
INSERT INTO estados ( NOMBRE) VALUES ('Baja California');
INSERT INTO estados (NOMBRE) VALUES ('Baja California Sur');
INSERT INTO estados ( NOMBRE) VALUES ('Campeche');
INSERT INTO estados ( NOMBRE) VALUES ('Chiapas');
INSERT INTO estados ( NOMBRE) VALUES ('Chihuahua');
INSERT INTO estados ( NOMBRE) VALUES ('Coahuila');
INSERT INTO estados ( NOMBRE) VALUES ('Colima');
INSERT INTO estados ( NOMBRE) VALUES ('Durango');
INSERT INTO estados ( NOMBRE) VALUES ('Guanajuato');
INSERT INTO estados ( NOMBRE) VALUES ('Guerrero');
INSERT INTO estados ( NOMBRE) VALUES ('Hidalgo');
INSERT INTO estados ( NOMBRE) VALUES ('Jalisco');
INSERT INTO estados ( NOMBRE) VALUES ('Estado de Mexico');
INSERT INTO estados ( NOMBRE) VALUES ('Michoacán');
INSERT INTO estados ( NOMBRE) VALUES ('Morelos');
INSERT INTO estados ( NOMBRE) VALUES ('Nayarit');
INSERT INTO estados ( NOMBRE) VALUES ('Nuevo León');
INSERT INTO estados ( NOMBRE) VALUES ('Oaxaca');
INSERT INTO estados ( NOMBRE) VALUES ('Puebla');
INSERT INTO estados ( NOMBRE) VALUES ('Querétaro');
INSERT INTO estados ( NOMBRE) VALUES ('Quintana Roo');
INSERT INTO estados ( NOMBRE) VALUES ('San Luis Potosí');
INSERT INTO estados ( NOMBRE) VALUES ('Sinaloa');
INSERT INTO estados ( NOMBRE) VALUES ('Sonora');
INSERT INTO estados ( NOMBRE) VALUES ('Tabasco');
INSERT INTO estados ( NOMBRE) VALUES ('Tamaulipas');
INSERT INTO estados ( NOMBRE) VALUES ('Tlaxcala');
INSERT INTO estados ( NOMBRE) VALUES ('Veracruz');
INSERT INTO estados ( NOMBRE) VALUES ('Yucatán');
INSERT INTO estados ( NOMBRE) VALUES ('Zacatecas');
INSERT INTO estados (NOMBRE) VALUES ('Ciudad de Mexico');

COMMIT; -- Confirmar las inserciones

-- Inserción de datos en la tabla ESPECIALIDAD
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Cardiología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Dermatología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Endocrinología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Gastroenterología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Ginecología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Hematología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Infectología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Neumología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Neurología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Nefrología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Oftalmología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Oncología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Pediatría');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Psiquiatría');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Reumatología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Traumatología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Urología');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Cirugía General');
INSERT INTO especialidad ( NOMBRE) VALUES ( 'Cirugía Plástica');

COMMIT; -- Confirmar las inserciones

-- Inserción de datos en la tabla PACIENTE
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Carmen', 'Ramírez', 'López', 'M', '01', '1234567805', '16', TO_DATE('1992-03-30', 'YYYY-MM-DD'), 'carmenr', 'Durango', 'Centro Histórico', '34000', ' 16 de Septiembre', 116, '016', 'password16', 15);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'María', 'Lopez', 'Martínez', 'M', '01', '1234567891', '12', TO_DATE('1990-02-15', 'YYYY-MM-DD'), 'maria01', 'Guadalajara', 'Lindavista', '44100', ' Reforma', 2, '002', 'password2', 1);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Carlos', 'Sánchez', 'Hernández', 'H', '01', '1234567892', '13', TO_DATE('1982-07-20', 'YYYY-MM-DD'), 'carl01', 'Monterrey', 'Centro', '64000', 'Avenida Juárez', 3, '003', 'password3', 3);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Ana', 'Ramírez', 'Torres', 'M', '01', '1234567893', '34', TO_DATE('1995-11-30', 'YYYY-MM-DD'), 'ana04', 'Tijuana', 'Playas de Tijuana', '22000', 'Calle 5 de Febrero', 4, '004', 'password4', 4);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Luis', 'González', 'Paredes', 'H', '01', '1234567894', '15', TO_DATE('1988-03-25', 'YYYY-MM-DD'), 'luis01', 'Cancún', 'Aldea Zama', '77500', 'Calle Libertad', 5, '005', 'password5', 6);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Patricia', 'Álvarez', 'Vargas', 'M', '01', '1234567895', '16', TO_DATE('1992-08-14', 'YYYY-MM-DD'), 'patri01', 'Puebla', 'La Paz', '72000', 'Calle Oaxaca', 6, '006', 'password6', 7);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Ricardo', 'Mendoza', 'Ríos', 'H', '01', '1234567896', '47', TO_DATE('1980-12-05', 'YYYY-MM-DD'), 'ricar01', 'Veracruz', 'Centro Histórico', '91700', 'Avenida Morelos', 7, '007', 'password7', 8);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Elena', 'Gutiérrez', 'Díaz', 'M', '01', '1234567897', '47', TO_DATE('1991-09-17', 'YYYY-MM-DD'), 'elen01', 'León', 'El Roble', '37200', 'Calle Bolívar', 8, '8', 'password8', 8);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'José', 'Martínez', 'Flores', 'H', '01', '1234567898', '47', TO_DATE('1986-04-30', 'YYYY-MM-DD'), 'jose01', 'Chihuahua', 'San Felipe', '31100', 'Calle del Carmen', 9, '009', 'password9', 9);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Isabel', 'Castro', 'Jiménez', 'M', '01', '1234567899', '10', TO_DATE('1993-06-22', 'YYYY-MM-DD'), 'isabe01', 'Toluca', 'Las Palomas', '50000', 'Calle Juárez', 10, '010', 'password10', 10);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Roberto', 'Serrano', 'Mendoza', 'H', '01', '1234567800', '11', TO_DATE('1984-01-10', 'YYYY-MM-DD'), 'rober01', 'Saltillo', 'Nueva Rosita', '25000', 'Av 16 de Septiembre', 11, '011', 'password11', 11);
--VERIFICAR 
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Sofía', 'Fernández', 'Pérez', 'M', '01', '1234567801', '12', TO_DATE('1994-10-04', 'YYYY-MM-DD'), 'sofia01', 'Mérida', 'El Rosario', '97000', 'Las Palmas', 11, '012', 'password12', 11);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Laura', 'Moreno', 'Vega', 'M', '01', '1234567803', '14', TO_DATE('1996-01-28', 'YYYY-MM-DD'), 'laura01', 'Oaxaca', 'Zimatan', '68000', 'Hidalgo', 14, '014', 'password14', 14);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Fernando', 'Jiménez', 'González', 'H', '01', '1234567804', '15', TO_DATE('1987-02-12', 'YYYY-MM-DD'), 'fern01', 'Chihuahua', 'Las Ánimas', '31150', 'Av Constitución', 15, '015', 'password15', 15);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Carmen', 'Ramírez', 'López', 'M', '01', '1234567805', '16', TO_DATE('1992-03-30', 'YYYY-MM-DD'), 'carme01', 'Durango', 'Centro Histórico', '34000', '16 de Septiembre', 16, '016', 'password16', 15);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Antonio', 'Jiménez', 'Silva', 'H', '01', '1234567806', '17', TO_DATE('1989-05-22', 'YYYY-MM-DD'), 'anton01', 'Culiacán', 'Lomas del Sol', '80000', 'Av de las Américas', 17, '017', 'password17', 15);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Pedro', 'Reyes', 'García', 'H', '01', '1234567808', '19', TO_DATE('1984-12-10', 'YYYY-MM-DD'), 'pedro01', 'Tuxpan', 'Centro', '92800', 'Av López Mateos', 19, '019', 'password19', 19);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Eduardo', 'Vázquez', 'Ramírez', 'H', '01', '1234567802', '13', TO_DATE('1983-11-18', 'YYYY-MM-DD'), 'eduard1', 'Querétaro', 'El Marqués', '76000', 'Av Benito Juárez', 13, '013', 'password13', 15);
INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Margarita', 'Cervantes', 'Ríos', 'M', '01', '1234567807', '18', TO_DATE('1980-09-25', 'YYYY-MM-DD'), 'margar1', 'Culiacán', 'Real de Culiacán', '80010', 'Valle', 18, '018', 'password18', 15);

INSERT INTO PACIENTE (
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, SEXO, LADA, TELEFONO, EXTENSION, 
    FECHA_NACIMIENTO, USUARIO, ALCAL_MUN, COLONIA, CP, CALLE, EXT, INTER, CONTRASENIA, ESTADO_ID
) 
VALUES
( 'Guadalupe', 'Torres', 'Luna', 'M', '01', '1234567809', '20', TO_DATE('1990-08-19', 'YYYY-MM-DD'), 'guadal2', 'Mazatlán', 'Sábalo Country', '82100', 'Morelos', 20, '020', 'password20', 19);

--Inserccion de datos en tabla MEDICO
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT,HORARIO, USUARIO, CONTRASENIA,ESPEC_ID
) 
VALUES
( 'Fernando', 'Jiménez', 'González',TO_DATE('2024-11-14 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'fern92', 'password27',5);
-- Inserción 2
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Ana', 'Rodríguez', 'Martínez', TO_DATE('2024-11-14 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ana92', 'password28', 1);

-- Inserción 3
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Carlos', 'López', 'Pérez', TO_DATE('2024-11-14 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'carloP', 'password29', 4);

-- Inserción 4
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Luisa', 'González', 'Torres', TO_DATE('2024-11-14 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'luisG', 'password30',4);

-- Inserción 5
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Eduardo', 'Hernández', 'Vásquez', TO_DATE('2024-11-14 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'edu95', 'password31', 4);

-- Inserción 6
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Patricia', 'Sánchez', 'Ramírez', TO_DATE('2024-11-14 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'patriS', 'password32', 6);

-- Inserción 7
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Roberto', 'García', 'Méndez', TO_DATE('2024-11-14 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'roberG', 'password33', 7);

-- Inserción 8
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'José', 'Martínez', 'Torres', TO_DATE('2024-11-14 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'joseM', 'password34', 1);

-- Inserción 9
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Raquel', 'Vázquez', 'López', TO_DATE('2024-11-14 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'raqueL', 'password35', 9);

-- Inserción 10
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Andrés', 'Pérez', 'Molina', TO_DATE('2024-11-14 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'andresP', 'password36', 10);

-- Inserción 11
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Sofía', 'Moreno', 'Jiménez', TO_DATE('2024-11-14 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'sofiaM', 'password37', 11);

-- Inserción 12
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Javier', 'Ramírez', 'González', TO_DATE('2024-11-14 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'javieR', 'password38', 12);


-- Inserción 14
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'José', 'Torres', 'Serrano', TO_DATE('2024-11-14 22:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'joseT', 'password40', 15);

-- Inserción 15
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Victoria', 'Cano', 'Castro', TO_DATE('2024-11-14 23:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'victorC', 'password41', 15);

-- Inserción 13
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Daniela', 'Reyes', 'Fernández', TO_DATE('2024-11-14 21:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'danieR', 'password39', 20);
-- Inserción 16
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Ricardo', 'Flores', 'Martínez', TO_DATE('2024-11-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ricarF', 'password42', 19);

-- Inserción 17
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Verónica', 'Vega', 'Salazar', TO_DATE('2024-11-15 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'veronV', 'password43', 19);

-- Inserción 18
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Eduardo', 'Córdoba', 'González', TO_DATE('2024-11-15 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'eduC98', 'password44', 19);

-- Inserción 19
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Santiago', 'López', 'Ruiz', TO_DATE('2024-11-15 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'santiL', 'password45', 18);

-- Inserción 20
INSERT INTO MEDICO(
     NOMBRE, APELLIDO_PAT, APELLIDO_MAT, HORARIO, USUARIO, CONTRASENIA, ESPEC_ID
) 
VALUES
( 'Claudia', 'Díaz', 'Ramírez', TO_DATE('2024-11-15 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'claudiD', 'password46', 17);

--Inserccion de tabla CITAS

INSERT INTO CITAS(
    FECHA_HORA_CITA,ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
(TO_DATE('2024-11-14 15:00:00', 'YYYY-MM-DD HH24:MI:SS'),'p',201,81,3);
-- Inserción 1
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 101, 82, 2);

-- Inserción 2
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-16 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 102, 83, 3);

-- Inserción 3
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-17 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 103, 84, 4);

-- Inserción 4
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-18 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 104, 85, 5);

-- Inserción 5
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-19 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 105, 86, 6);

-- Inserción 6
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-20 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 106, 91, 7);

-- Inserción 7
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-21 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 107, 97, 8);

-- Inserción 8
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-22 15:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 108, 92, 9);

-- Inserción 9
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-23 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 109, 93, 10);

-- Inserción 10
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-24 08:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 110, 98, 1);

-- Inserción 11
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-25 13:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 201, 85, 11);

-- Inserción 12
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-26 16:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 202, 89, 12);

-- Inserción 13
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-27 10:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 203, 96, 13);

-- Inserción 14
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-28 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 204, 100, 2);

-- Inserción 15
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-29 14:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 205, 91, 14);

-- Inserción 16
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-11-30 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 206, 100, 15);

-- Inserción 17
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-12-01 13:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 207, 82, 16);

-- Inserción 18
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-12-02 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'p', 208, 92, 17);

-- Inserción 19
INSERT INTO CITAS(
     FECHA_HORA_CITA, ESTADO_CITA, NUMERO_CONSULTORIO, PACIENTE_ID, MEDICO_ID
) 
VALUES
( TO_DATE('2024-12-03 10:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'c', 209, 95, 18);

--Inserccion tabla DIAGNOSTICO
INSERT INTO DIAGNOSTICO(
    DIAGNOSTICO,CITA_ID
) 
VALUES
('Gastritis',1);
-- Inserción 2
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Arritmia', 2); -- Cardiología

-- Inserción 3
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Gastritis', 3); -- Gastroenterología

-- Inserción 4
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Úlcera Péptica', 4); -- Gastroenterología

-- Inserción 5
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Colitis', 5); -- Gastroenterología

-- Inserción 6
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Quiste Ovárico', 6); -- Ginecología

-- Inserción 7
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Anemia', 7); -- Hematología

-- Inserción 8
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Hepatitis B', 8); -- Infectología

-- Inserción 9
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Migraña', 9); -- Neurología

-- Inserción 10
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Insuficiencia Renal', 10); -- Nefrología

-- Inserción 11
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Cataratas', 11); -- Oftalmología

-- Inserción 12
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Cáncer de Mama', 12); -- Oncología

-- Inserción 13
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Depresión Mayor', 13); -- Psiquiatría

-- Inserción 14
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Ansiedad', 14); -- Psiquiatría

-- Inserción 15
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Apendicitis', 15); -- Cirugía General

-- Inserción 16
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Hernia Inguinal', 16); -- Cirugía General

-- Inserción 17
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Colecistitis', 17); -- Cirugía General

-- Inserción 18
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Fractura de Brazo', 18); -- Cirugía General

-- Inserción 19
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Fractura de Pierna', 19); -- Cirugía General

-- Inserción 20
INSERT INTO DIAGNOSTICO(
     DIAGNOSTICO, CITA_ID
) 
VALUES
( 'Rinoplastia', 20); -- Cirugía Plástica

--Inserccion tabla PADECIMIENTO
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Gastritis');
-- Inserción 2
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Arritmia'); -- Cardiología

-- Inserción 3
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Gastritis'); -- Gastroenterología

-- Inserción 4
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Úlcera Péptica'); -- Gastroenterología

-- Inserción 5
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Colitis'); -- Gastroenterología

-- Inserción 6
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Quiste Ovárico'); -- Ginecología

-- Inserción 7
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Anemia'); -- Hematología

-- Inserción 8
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Hepatitis B'); -- Infectología

-- Inserción 9
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Migraña'); -- Neurología

-- Inserción 10
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Insuficiencia Renal'); -- Nefrología

-- Inserción 11
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Cataratas'); -- Oftalmología

-- Inserción 12
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Cáncer de Mama'); -- Oncología

-- Inserción 13
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Depresión Mayor'); -- Psiquiatría

-- Inserción 14
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Ansiedad'); -- Psiquiatría

-- Inserción 15
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Apendicitis'); -- Cirugía General

-- Inserción 16
INSERT INTO PADECIMIENTO(
   PADECIMIENTO
) 
VALUES
('Hernia Inguinal'); -- Cirugía General

-- Inserción 17
INSERT INTO PADECIMIENTO(
   PADECIMIENTO
) 
VALUES
('Colecistitis'); -- Cirugía General

-- Inserción 18
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Fractura de Brazo'); -- Cirugía General

-- Inserción 19
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Fractura de Pierna'); -- Cirugía General

-- Inserción 20
INSERT INTO PADECIMIENTO(
    PADECIMIENTO
) 
VALUES
('Rinoplastia'); -- Cirugía Plástica


--Inserccion tabla RECETA
INSERT INTO RECETA(
    MEDICO_ID,PACIENTE_ID,FECHA_EMISION,MEDICAMENTOS
) 
VALUES
(1,81,TO_DATE('2024-06-22','YYYY-MM-DD'),'Paracetamol');

-- Insercción tabla RECETA
INSERT INTO RECETA (
    MEDICO_ID, PACIENTE_ID, FECHA_EMISION, MEDICAMENTOS
)
VALUES
(2, 82, TO_DATE('2024-06-23','YYYY-MM-DD'), 'Ibuprofeno');
INSERT INTO RECETA (
    MEDICO_ID, PACIENTE_ID, FECHA_EMISION, MEDICAMENTOS
)
VALUES
(5, 85, TO_DATE('2024-06-24','YYYY-MM-DD'), 'Amoxicilina');
INSERT INTO RECETA (
    MEDICO_ID, PACIENTE_ID, FECHA_EMISION, MEDICAMENTOS
)
VALUES
(8, 88, TO_DATE('2024-06-25','YYYY-MM-DD'), 'Metformina');
INSERT INTO RECETA (
    MEDICO_ID, PACIENTE_ID, FECHA_EMISION, MEDICAMENTOS
)
VALUES
(12, 92, TO_DATE('2024-06-26','YYYY-MM-DD'), 'Loratadina');
INSERT INTO RECETA (
    MEDICO_ID, PACIENTE_ID, FECHA_EMISION, MEDICAMENTOS
)
VALUES
(19, 99, TO_DATE('2024-06-27','YYYY-MM-DD'), 'Omeprazol');

-- Inserccion PACIENTE_PADECIMIENTO
INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (81, 'Paciente en tratamiento', 1);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (82, 'Paciente en tratamiento', 2);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (83, 'Mejora lenta pero constante', 3);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (84, 'Seguimiento mensual necesario', 4);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (85, 'Tratamiento preventivo aplicado', 5);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (86, 'Condición estable', 6);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (87, 'No presenta síntomas graves', 7);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (88, 'Sigue en observación médica', 8);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (89, 'Mejoría en síntomas', 9);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (90, 'Requiere revisión trimestral', 10);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (91, 'Condición bajo control', 11);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (92, 'Sin cambios desde la última cita', 12);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (93, 'Tratamiento reciente iniciado', 13);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (94, 'Se necesita seguimiento', 14);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (95, 'Sintomatología leve', 15);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (96, 'Aún presenta síntomas', 16);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (97, 'Requiere control mensual', 17);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (98, 'Presenta mejora significativa', 18);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (99, 'Evolución favorable', 19);

INSERT INTO PACIENTE_PADECIMIENTO (PACIENTE_ID, OBSERVACION, PADECIMIENTO_ID)
VALUES (100, 'Control cada seis meses', 20);
