CREATE TABLE ESTADO(
    ESTADO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    CONSTRAINT ESTADO_PK PRIMARY KEY (ESTADO_ID)
);

CREATE TABLE PACIENTE (
    PACIENTE_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    APELLIDO_PAT VARCHAR2(20),
    APELLIDO_MAT VARCHAR2(20),
    SEXO VARCHAR2(2),
    LADA VARCHAR2(7),
    TELEFONO VARCHAR2(20),
    EXTENSION VARCHAR2(2),
    FECHA_NACIMIENTO DATE,
    USUARIO VARCHAR2(7),
    ESTADO_ID VARCHAR2(7),
    ALCALMUN VARCHAR2(20),
    COLONIA VARCHAR2(20),
    CP VARCHAR2(7),
    CALLE VARCHAR2(20),
    EXT VARCHAR2(7),
    INT VARCHAR2(7),
    USUARIO_USUARIO_ID VARCHAR2(7),
    CONTRASENA VARCHAR2(20),
    ESTADO_ESTADO_ID VARCHAR(7),
    CONSTRAINT PACIENTE_PK PRIMARY KEY (PACIENTE_ID),
    CONSTRAINT PACIENTE_ESTADO_FK FOREIGN KEY (ESTADO_ESTADO_ID) REFERENCES ESTADO(ESTADO_ID)
);

CREATE TABLE EMPLEADO (
    EMPLEADO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    APELLIDO_PAT VARCHAR2(20),
    APELLIDO_MAT VARCHAR2(20),
    FECHA_INGRESO DATE,
    FECHA_NACIMIENTO DATE,
    USUARIO_USUARIO_ID VARCHAR2(7),
    ESTADO_ID VARCHAR2(7),
    PACIENTE_PACIENTE_ID VARCHAR2(7),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID),
    CONSTRAINT EMPLEADO_PACIENTE_FK FOREIGN KEY (PACIENTE_PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID)
);

CREATE TABLE PUESTO (
    PUESTO_ID VARCHAR2(20),
    PUESTO VARCHAR2(20),
    EMPLEADO_EMPLEADO_ID VARCHAR2(7),
    CONSTRAINT PUESTO_PK PRIMARY KEY (PUESTO_ID),
    CONSTRAINT PUESTO_EMPLEADO_FK FOREIGN KEY (EMPLEADO_EMPLEADO_ID) REFERENCES EMPLEADO(EMPLEADO_ID)
);

CREATE TABLE ESPECIALIDAD (
    ESPEC_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY (ESPEC_ID)
);

CREATE TABLE MEDICO (
    MEDICO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    APELLIDO_PAT VARCHAR2(20),
    APELLIDO_MAT VARCHAR2(20),
    HORARIO DATE,
    USUARIO VARCHAR2(20),
    CONTRASENA VARCHAR2(20),
    ESPECIALIDAD_ESPEC_ID VARCHAR2(7),
    CONSTRAINT MEDICO_PK PRIMARY KEY (MEDICO_ID),
    CONSTRAINT MEDICO_ESPECIALIDAD_FK FOREIGN KEY (ESPECIALIDAD_ESPEC_ID) REFERENCES ESPECIALIDAD(ESPEC_ID)
);

CREATE TABLE CITAS (
    CITAS_ID VARCHAR2(7),
    MEDICO_ID VARCHAR2(7),
    FECHA_HORA_CITA DATE,
    ESTADO_CITA VARCHAR2(7),
    USUARIO_ID VARCHAR2(7),
    NUM_CONSULTORIO VARCHAR2(20),
    USUARIO_USUARIO_ID VARCHAR2(7),
    PACIENTE_PACIENTE_ID VARCHAR2(7),
    MEDICO_MEDICO_ID VARCHAR2(7),
    CONSTRAINT CITAS_PK PRIMARY KEY (CITAS_ID),
    CONSTRAINT CITAS_PACIENTE_FK FOREIGN KEY (PACIENTE_PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID),
    CONSTRAINT CITAS_MEDICO_FK FOREIGN KEY (MEDICO_MEDICO_ID) REFERENCES MEDICO(MEDICO_ID)
);

CREATE TABLE PADECIMIENTO (
    PADECIMIENTO_ID VARCHAR2(7),
    PADECIMIENTO VARCHAR2(20),
    CONSTRAINT PADECIMIENTO_PK PRIMARY KEY (PADECIMIENTO_ID)
);

CREATE TABLE PACIENTE_PADECIMIENTO (
    PACIENTE_ID VARCHAR2(7),
    PADECIMIENTO_ID VARCHAR2(7),
    PACIENTE_PACIENTE_ID VARCHAR2(7),
    PADECIMIENTO_PADECIMIENTO VARCHAR2(20),
    PADECIMIENTO_PADECIMIENTO_ID VARCHAR2(7),
    CONSTRAINT PACIENTE_PADECIMIENTO_PK PRIMARY KEY (PACIENTE_ID, PADECIMIENTO_ID),
    CONSTRAINT PACIENTE_PADECIMIENTO_PACIENTE_FK FOREIGN KEY (PACIENTE_PACIENTE_ID) REFERENCES PACIENTE(PACIENTE_ID),
    CONSTRAINT PACIENTE_PADECIMIENTO_PADECIMIENTO_FK FOREIGN KEY (PADECIMIENTO_PADECIMIENTO_ID) REFERENCES PADECIMIENTO(PADECIMIENTO_ID)
);

CREATE TABLE DIAGNOSTICO (
    DIAGNOSTICO_ID VARCHAR2(7),
    DIAGNOSTICO VARCHAR2(600),
    CITAS_PACIENTE_ID VARCHAR2(7),
    CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY (DIAGNOSTICO_ID),
    CONSTRAINT DIAGNOSTICO_CITAS_FK FOREIGN KEY (CITAS_PACIENTE_ID) REFERENCES CITAS(CITAS_ID)
);

CREATE TABLE MEDICAMENTO (
    MEDICAMENTO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (MEDICAMENTO_ID)
);

CREATE TABLE RECETA (
    DIAGNOSTICO_ID VARCHAR2(7),
    MEDICAMENTO_ID VARCHAR2(7),
    CITAS_PACIENTE_ID VARCHAR(7),
    PERIODICIDAD VARCHAR2(20),
    MEDICAMENTO_MEDICAMENTO_ID VARCHAR(7),
    CONSTRAINT RECETA_PK PRIMARY KEY (DIAGNOSTICO_ID),
    CONSTRAINT RECETA_CITAS_FK FOREIGN KEY (CITAS_PACIENTE_ID) REFERENCES CITAS(CITAS_ID),
    CONSTRAINT RECETA_MEDICAMENTO_FK FOREIGN KEY (MEDICAMENTO_MEDICAMENTO_ID) REFERENCES MEDICAMENTO(MEDICAMENTO_ID)
);

CREATE TABLE COMPONENTE (
    COMP_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    MEDICAMENTO_MEDICAMENTO_ID VARCHAR2(7),
    CONSTRAINT COMPONENTE_PK PRIMARY KEY (COMP_ID),
    CONSTRAINT COMPONENTE_MEDICAMENTO_FK FOREIGN KEY (MEDICAMENTO_MEDICAMENTO_ID) REFERENCES MEDICAMENTO(MEDICAMENTO_ID)
);
CREATE TABLE MEDI_COMP (
    MED_ID VARCHAR2(7),
    COMP_ID VARCHAR2(7),
    COMPONENTE_COMP_ID VARCHAR2(7),
    CONSTRAINT MEDI_COMP_PK PRIMARY KEY (MED_ID, COMP_ID),
    CONSTRAINT MEDI_COMP_MEDICAMENTO_FK FOREIGN KEY (MED_ID) REFERENCES MEDICAMENTO(MEDICAMENTO_ID),
    CONSTRAINT MEDI_COMP_COMPONENTE_FK FOREIGN KEY (COMPONENTE_COMP_ID) REFERENCES COMPONENTE(COMP_ID)
);