-- CAMBIA DE REPOSITORIO
ALTER SESSION SET CONTAINER=XEPDB1;

-- SE CREA EL TABLESPACE
--Cambiar USR por el nombre de usuario de la computadora 
CREATE TABLESPACE TBS_CITAS
DATAFILE 'C:\app\Giovani\product\18.0.0\oradata\XE\XEPDB1\tbs_citas.dbf'
SIZE 100M 
AUTOEXTEND ON NEXT 10 M
MAXSIZE 200M
ONLINE;

-- SE CREA EL USUARIO
CREATE USER usr_citas
IDENTIFIED BY citapass
DEFAULT TABLESPACE TBS_CITAS
QUOTA UNLIMITED ON TBS_CITAS;

-- SE CREA EL ROL
CREATE ROLE DESARROLLADOR;

-- SE ASINGNAN LOS PRIVILEGIOS AL ROL
-- si ya tienen creado este rol, omitir este paso
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE,
      INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE, 
      CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE, EXECUTE ANY PROCEDURE
      TO DESARROLLADOR;

-- SE ASIGNA EL ROL AL USUARIO (rol ue ya está creado)
GRANT DESARROLLADOR TO usr_citas;


-- Para Borrar el usuario
--DROP USER USR_RENTA CASCADE;

-- Para Borrar el tablespace
--DROP TABLESPACE TBS_RENTA
--INCLUDING CONTENTS AND DATAFILES;

-- Para borrar el rol
--DROP ROLE PROGRAMADOR;