-- Tabla: ESTADOS
CREATE TABLE ESTADO (
    ESTADO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    CONSTRAINT ESTADO_PK PRIMARY KEY (ESTADO_ID)
);

-- Tabla: PACIENTE
CREATE TABLE PACIENTE (
    PACIENTE_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    APELLIDO_PAT VARCHAR2(20),
    APELLIDO_MAT VARCHAR2(20),
    SEXO VARCHAR2(1),
    LADA VARCHAR2(5),
    TELEFONO VARCHAR2(15),
    EXT VARCHAR2(7),
    INTER VARCHAR2(7),
    EXTENSION VARCHAR2(10),
    FECHA_NACIMIENTO DATE,
    USUARIO VARCHAR2(20),
    CONTRASENIA VARCHAR2(20),
    ESTADO_ID VARCHAR2(7),
    CALLE VARCHAR2(50),
    ALCAL_MUN VARCHAR2(50),
    COLONIA VARCHAR2(50),
    CP VARCHAR2(5),
    CONSTRAINT FK_ESTADO FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ESTADO_ID),
    CONSTRAINT PACIENTE_PK PRIMARY KEY (PACIENTE_ID)
);




-- Tabla: PUESTO
CREATE TABLE PUESTO (
    PUESTO_ID VARCHAR2(7),
    PUESTO VARCHAR2(20),
    CONSTRAINT PUESTO_PK PRIMARY KEY (PUESTO_ID)
);

-- Tabla: EMPLEADO
CREATE TABLE EMPLEADO (
    EMPLEADO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    APELLIDO_PAT VARCHAR2(20),
    APELLIDO_MAT VARCHAR2(20),
    FECHA_INGRESO DATE,
    FECHA_NACIMIENTO DATE,
    USUARIO VARCHAR2(20),
    CONTRASENIA VARCHAR2(20),
    PACIENTE_ID VARCHAR2(7 BYTE),
    PUESTO_ID VARCHAR2(7 BYTE),
    CONSTRAINT FK_PACIENTE FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE (PACIENTE_ID),
    CONSTRAINT FK_PUESTO FOREIGN KEY (PUESTO_ID) REFERENCES PUESTO (PUESTO_ID),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID)
);

-- Tabla: ESPECIALIDAD
CREATE TABLE ESPECIALIDAD (
    ESPEC_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    CONSTRAINT ESPECIALIDAD_PK PRIMARY KEY (ESPEC_ID)
);


-- Tabla: MEDICO
CREATE TABLE MEDICO (
    MEDICO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    APELLIDO_PAT VARCHAR2(20),
    APELLIDO_MAT VARCHAR2(20),
    HORARIO TIMESTAMP(6),
    USUARIO VARCHAR2(20),
    CONTRASENIA VARCHAR2(20),
    ESPEC_ID VARCHAR2(7 ),
    CONSTRAINT FK_ESPEC FOREIGN KEY (ESPEC_ID) REFERENCES ESPECIALIDAD (ESPEC_ID),
    CONSTRAINT MEDICO_PK PRIMARY KEY (MEDICO_ID)

);


-- Tabla: CITAS
CREATE TABLE CITAS (
    CITAS_ID VARCHAR2(7),
    FECHA_HORA_CITA TIMESTAMP(6),
    ESTADO_CITA VARCHAR2(20),
    NUM_CONSULTORIO VARCHAR2(7),
    PACIENTE_ID VARCHAR2(7 ),
    MEDICO_ID VARCHAR2(7 ),
    CONSTRAINT FK_PACIENTE2 FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE (PACIENTE_ID),
    CONSTRAINT FK_MEDICO FOREIGN KEY (MEDICO_ID) REFERENCES MEDICO (MEDICO_ID),
    CONSTRAINT CITAS_PK PRIMARY KEY (CITAS_ID)
);

-- Tabla: PADECIMIENTO
CREATE TABLE PADECIMIENTO (
    PADECIMIENTO_ID VARCHAR2(7),
    PADECIMIENTO VARCHAR2(20),
    CONSTRAINT PK_PADECIMIENTO PRIMARY KEY (PADECIMIENTO_ID)
);

-- Tabla: PACIENTE_PADECIMIENTO
CREATE TABLE PACIENTE_PADECIMIENTO (
    PACIENTE_ID VARCHAR2(7),
    OBSERVACION VARCHAR2(33 ),
    PADECIMIENTO_ID VARCHAR2(7),
    CONSTRAINT PK_PACIENTE_PADECIMIENTO PRIMARY KEY (PACIENTE_ID, PADECIMIENTO_ID),
    CONSTRAINT FK_PACIENTE3 FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE (PACIENTE_ID),
    CONSTRAINT FK_PADECIMIENTO FOREIGN KEY (PADECIMIENTO_ID) REFERENCES PADECIMIENTO (PADECIMIENTO_ID)
);

-- Tabla: DIAGNOSTICO
CREATE TABLE DIAGNOSTICO (
    DIAGNOSTICO_ID VARCHAR2(7),
    DIAGNOSTICO VARCHAR2(600),
    CITAS_ID VARCHAR2(7 ),
    CONSTRAINT FK_CITAS FOREIGN KEY (CITAS_ID) REFERENCES CITAS (CITAS_ID),
    CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY (DIAGNOSTICO_ID)
);

-- Tabla: MEDICAMENTO
CREATE TABLE MEDICAMENTO (
    MEDICAMENTO_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (MEDICAMENTO_ID)
);

-- Tabla: RECETA
CREATE TABLE RECETA (
    DIAGNOSTICO_ID VARCHAR2(7),
    MEDICAMENTO_ID VARCHAR2(7 ),
    PERIODICIDAD VARCHAR2(25),
    CONSTRAINT FK_DIAGNOSTICO FOREIGN KEY (DIAGNOSTICO_ID) REFERENCES DIAGNOSTICO (DIAGNOSTICO_ID),
    CONSTRAINT FK_MEDICAMENTO3 FOREIGN KEY (MEDICAMENTO_ID) REFERENCES MEDICAMENTO (MEDICAMENTO_ID),
    CONSTRAINT PK_RECETA PRIMARY KEY (DIAGNOSTICO_ID)
);


-- Tabla: MED_COMP
CREATE TABLE MED_COMP (
    MED_ID VARCHAR2(7),
    MEDICAMENTO_ID VARCHAR2(7),
    CONSTRAINT MED_COMP_PK PRIMARY KEY (MED_ID, MEDICAMENTO_ID),
    CONSTRAINT FK_MEDICAMENTO FOREIGN KEY (MEDICAMENTO_ID) REFERENCES MEDICAMENTO (MEDICAMENTO_ID)
);

-- Tabla: COMPUESTO
CREATE TABLE COMPUESTO (
    COMP_ID VARCHAR2(7),
    NOMBRE VARCHAR2(20),
    MED_ID VARCHAR2(7 ),
    MEDICAMENTO_ID VARCHAR2(7),
    CONSTRAINT FK_MEDICAMENTO2 FOREIGN KEY (MED_ID, MEDICAMENTO_ID) REFERENCES MED_COMP (MED_ID, MEDICAMENTO_ID),
    CONSTRAINT COMPONENTE_PK PRIMARY KEY (COMP_ID)
);
